language: python
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=4.3
    - python: 2.7
      env: PLONE_VERSION=5.2
install:
  - mkdir -p buildout-cache/downloads
  - cp requirements-$PLONE_VERSION.txt requirements.txt
  - pip install -r requirements.txt --force-reinstall --install-option="--install-scripts=${PWD}/bin
  - bin/buildout -c test-$PLONE_VERSION.cfg
script:
  - bin/test
